[package]
name = "shakmaty-syzygy-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
shakmaty = "0.21"
shakmaty-syzygy = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "pawnful"
path = "fuzz_targets/pawnful.rs"
