language: rust
sudo: false

rust:
 - 1.24.0
 - 1.25.0
 - 1.26.0
 - 1.27.0
 - stable
 - beta
 - nightly

cache:
  directories:
   - tables

before_install:
 - ./download-test-tables.sh

before_cache:
 - rm -f tables/**/*.txt
