language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

cache:
  directories:
    - tables

before_install:
  - ./download-test-tables.sh

test:
  - cargo test
  - cargo test --all-features
  - [[ $(rustc --version) =~ "nightly" ]] && cargo test -Z minimal-versions
  - [[ $(rustc --version) =~ "nightly" ]] && cargo test -Z minimal-versions --all-features
  - cargo doc
  - cargo doc --all-features

before_cache:
  - rm -f tables/**/*.txt
