name: Clippy
on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack

      - name: Main
        run: cargo hack clippy --feature-powerset --all-targets -- --deny warnings
      - name: Fuzz
        run: cargo hack clippy --feature-powerset --manifest-path fuzz/Cargo.toml --all-targets -- --deny warnings